"""HTTP status codes, exceptions, and validation utilities."""

from pyhttp_util.status.exceptions import (
    BadGatewayError,
    BadRequestError,
    ClientError,
    ConflictError,
    ContentTooLargeError,
    ExpectationFailedError,
    FailedDependencyError,
    ForbiddenError,
    GatewayTimeoutError,
    GoneError,
    HTTPStatusError,
    HTTPVersionNotSupportedError,
    ImATeapotError,
    InformationalResponse,
    InsufficientStorageError,
    InternalServerError,
    LengthRequiredError,
    LockedError,
    LoopDetectedError,
    MethodNotAllowedError,
    MisdirectedRequestError,
    NetworkAuthenticationRequiredError,
    NotAcceptableError,
    NotExtendedError,
    NotFoundError,
    NotImplementedError_,
    PaymentRequiredError,
    PreconditionFailedError,
    PreconditionRequiredError,
    ProxyAuthenticationRequiredError,
    RangeNotSatisfiableError,
    RedirectResponse,
    RequestHeaderFieldsTooLargeError,
    RequestTimeoutError,
    ServerError,
    ServiceUnavailableError,
    TooEarlyError,
    TooManyRequestsError,
    UnauthorizedError,
    UnavailableForLegalReasonsError,
    UnprocessableEntityError,
    UnsupportedMediaTypeError,
    UpgradeRequiredError,
    URITooLongError,
    VariantAlsoNegotiatesError,
    get_exception_for_status,
)
from pyhttp_util.status.status_enum import HTTPStatus
from pyhttp_util.status.validator import (
    StatusCodeValidator,
    StatusValidationError,
    StatusValidationResult,
)

__all__ = (
    # Enum
    "HTTPStatus",
    # Validator
    "StatusCodeValidator",
    "StatusValidationError",
    "StatusValidationResult",
    # Base exceptions
    "HTTPStatusError",
    "InformationalResponse",
    "RedirectResponse",
    "ClientError",
    "ServerError",
    # 4xx Client errors
    "BadRequestError",
    "UnauthorizedError",
    "PaymentRequiredError",
    "ForbiddenError",
    "NotFoundError",
    "MethodNotAllowedError",
    "NotAcceptableError",
    "ProxyAuthenticationRequiredError",
    "RequestTimeoutError",
    "ConflictError",
    "GoneError",
    "LengthRequiredError",
    "PreconditionFailedError",
    "ContentTooLargeError",
    "URITooLongError",
    "UnsupportedMediaTypeError",
    "RangeNotSatisfiableError",
    "ExpectationFailedError",
    "ImATeapotError",
    "MisdirectedRequestError",
    "UnprocessableEntityError",
    "LockedError",
    "FailedDependencyError",
    "TooEarlyError",
    "UpgradeRequiredError",
    "PreconditionRequiredError",
    "TooManyRequestsError",
    "RequestHeaderFieldsTooLargeError",
    "UnavailableForLegalReasonsError",
    # 5xx Server errors
    "InternalServerError",
    "NotImplementedError_",
    "BadGatewayError",
    "ServiceUnavailableError",
    "GatewayTimeoutError",
    "HTTPVersionNotSupportedError",
    "VariantAlsoNegotiatesError",
    "InsufficientStorageError",
    "LoopDetectedError",
    "NotExtendedError",
    "NetworkAuthenticationRequiredError",
    # Utility
    "get_exception_for_status",
)
